<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2017/11/23
 * Time: 17:51
 */

namespace app\components\widgets\components;


use yii\base\Widget;
use Yii;
use app\common\util\data;
use app\common\util\curl;

class BaseWidget extends Widget {
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *  获取/提交数据
     * @param $postData array
     * @param $url      string
     * @return mixed    返回结果
     */
    protected function getData($postData = array(), $url) {
        $rsData = array();
        $postData['token'] = Yii::$app -> session -> get('token');
        $postData = data::getData($postData);
        $rs = curl::curl_get_contents($url, '30', $postData);
        if (!empty($rs)) {
            $rsData = data::getResponseData($rs);
        }
        return $rsData;
    }
}