<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2018/7/17
 * Time: 14:34
 */

define('UPLOAD_IMG_TYPE','jpg,png,jpeg');

define('UPLOAD_IMG_SERVER_BUSINESS_LICENSE_FOLDER', 'unionpayBusinessLicense'); // 服务商营业执照
define('UPLOAD_IMG_SERVER_BUSINESS_LICENSE_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_BUSINESS_LICENSE_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_ZM_FOLDER', 'legalPersonIdCardZm'); // 服务商法人代表身份证正面
define('UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_ZM_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_ZM_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_FM_FOLDER', 'legalPersonIdCardFm'); // 服务商法人代表身份证反面
define('UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_FM_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_LEGAL_PERSON_ID_CARD_FM_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_CONTACT_ID_CARD_ZM_FOLDER', 'contactIdCardZm'); // 服务商身份证正面
define('UPLOAD_IMG_SERVER_CONTACT_ID_CARD_ZM_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_CONTACT_ID_CARD_ZM_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_CONTACT_ID_CARD_FM_FOLDER', 'contactIdCardFm'); // // 服务商身份证反面
define('UPLOAD_IMG_SERVER_CONTACT_ID_CARD_FM_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_CONTACT_ID_CARD_FM_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_ACCOUNT_OPENING_PERMIT_FOLDER', 'accountOpeningPermit'); // 服务商基本户开户许可证
define('UPLOAD_IMG_SERVER_ACCOUNT_OPENING_PERMIT_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_ACCOUNT_OPENING_PERMIT_FOLDER . '/source/');

define('UPLOAD_IMG_SERVER_GOODS_FOLDER', 'unionpayGoods'); // 商品图片
define('UPLOAD_IMG_SERVER_GOODS_SOURCE', FILES_BASE_PATH . UPLOAD_IMG_SERVER_GOODS_FOLDER . '/source/');