<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2018/7/17
 * Time: 9:35
 */

define('UPLOAD_DATA_TYPE', 'jpg,png,jpeg,doc,docx,pdf,xlsx,xls');
define('UPLOAD_ORDER_DATA_FOLDER', 'orderData');
define('UPLOAD_ORDER_DATA_SOURCE', FILES_BASE_PATH . UPLOAD_ORDER_DATA_FOLDER . '/source/');

define('ORDER_STATUS_OPERATION_AUDIT',1);//待运营方确认
define('ORDER_STATUS_ACTUALIZE',2);//进行中
define('ORDER_STATUS_UNPAID',3);//待付款
define('ORDER_STATUS_PAID_CONFIRM',4);//支付待确认
define('ORDER_STATUS_COMPLETED',5);//已完成
define('ORDER_STATUS_CANCEL',6);//已关闭
define('ORDER_STATUS_DEMANDER_AUDIT',7);//待需求方确认
define('ORDER_STATUS_MERCHANT_AUDIT',8);//待服务方确认


$GLOBALS['__ORDER_STATUS_LIST_SHOW'] = [
    ORDER_STATUS_OPERATION_AUDIT => '待运营方确认',
    ORDER_STATUS_ACTUALIZE => '进行中',
    ORDER_STATUS_UNPAID => '待付款',
    ORDER_STATUS_PAID_CONFIRM => '支付待确认',
    ORDER_STATUS_COMPLETED => '已完成',
    ORDER_STATUS_CANCEL => '已关闭',
    ORDER_STATUS_DEMANDER_AUDIT => '待需求方确认',
    ORDER_STATUS_MERCHANT_AUDIT => '待服务方确认'
];

//订单操作日志类型
define('ORDER_OPERATION_TYPE_CREATE',1);//创建订单
define('ORDER_OPERATION_TYPE_CONFIRM',2);//确认订单
define('ORDER_OPERATION_TYPE_RECREATE',3);//重新下单
define('ORDER_OPERATION_TYPE_EDIT',4);//修改服务
define('ORDER_OPERATION_TYPE_CANCEL',5);//结束订单
define('ORDER_OPERATION_TYPE_FINALPAYMENT_URGE',6);//催尾款
define('ORDER_OPERATION_TYPE_FINALPAYMENT_INFO',7);//填写支付信息
define('ORDER_OPERATION_TYPE_FINALPAYMENT_CONFIRM',8);//确认尾款收款
define('ORDER_OPERATION_TYPE_ADVANCEPAYMENT_URGE',9);//预付款催款
define('ORDER_OPERATION_TYPE_ADVANCEPAYMENT_INFO',10);//填写预付款支付信息
define('ORDER_OPERATION_TYPE_UPLOAD',11);//上传资料
define('ORDER_OPERATION_TYPE_ADVANCEPAYMENT_CONFIRM',12);//预付款确认
define('ORDER_OPERATION_TYPE_ADVANCEPAYMENT_REJECT',13);//预付款驳回
define('OPERATION_LOG_TYPE_SERVICE_PROVIDERS_REVOKE',14);//服务方审核撤回
$GLOBALS['__ORDER_OPERATION_TYPE'] = [
    ORDER_OPERATION_TYPE_CREATE => '提交订单',
    ORDER_OPERATION_TYPE_CONFIRM => '确认订单',
    ORDER_OPERATION_TYPE_RECREATE => '重新下单',
    ORDER_OPERATION_TYPE_EDIT => '修改服务',
    ORDER_OPERATION_TYPE_CANCEL => '结束订单',
    ORDER_OPERATION_TYPE_FINALPAYMENT_URGE => '催尾款',
    ORDER_OPERATION_TYPE_FINALPAYMENT_INFO => '填写支付信息',
    ORDER_OPERATION_TYPE_FINALPAYMENT_CONFIRM => '确认尾款收款',
    ORDER_OPERATION_TYPE_ADVANCEPAYMENT_URGE => '预付款催款',
    ORDER_OPERATION_TYPE_ADVANCEPAYMENT_INFO => '填写预付款支付信息',
    ORDER_OPERATION_TYPE_UPLOAD => '上传资料',
    ORDER_OPERATION_TYPE_ADVANCEPAYMENT_CONFIRM => '预付款确认',
    ORDER_OPERATION_TYPE_ADVANCEPAYMENT_REJECT => '预付款驳回',
    OPERATION_LOG_TYPE_SERVICE_PROVIDERS_REVOKE => '服务方审核撤回'

];